# order-service specific configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${ORDER_DB_PORT:25440}/order_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
